public Class A0
{
public Account createAccount(String name)  //method to create account
{//comment source line4 srcmodififylast.  jklbnkjhb
Account QDTest= new Account();
Account a01231111112331= new Account();
Account a0123111111233= new Account();
Account a0123111111= new Account(); //commentsourceasdasdasda line2 modify1
a0123111111.Name = name; //line3
return a0123111111; //line7 src modifylast1
//a211111111111111111111111
//007
}
}
